export type User = {
    authors: string;
    year: string;
    tittle: string;
    tag: string;
    added: string;
    file: string;
  };
  
  export const fakeData: User[] = [
    {
      authors: 'Iqra Aswad | Muhammad Niswar | Amil Ahmad Ilham',
      year: '2017',
      tittle: 'Pengembangan Media Proxy untuk Mendukung Komunikasi Real Time berbasis WEB',
      tag: 'webRTC',
      added: '30/01/2023',
      file: '',
    },
    {
      authors: 'KAmil Ahmad Ilham | Anugrayani Bustamin | Iqra Aswad |',
      year: '2020',
      tittle: 'Implementation of Clustering and Similarity Analysis for Detecing Content Similarity in Student Final Projects',
      tag: 'clustering, similarity',
      added: '15 April 2023',
      file: '',
    },
    {
      authors: 'Taslinda | Indrabayu | Anugrayani Bustamin',
      year: '2017',
      tittle: 'Sistem Deteksi Hambatan Pada Autonomous Driving',
      tag: 'autonomous driving, hambatan, SSD, mobilenet v2, real time',
      added: '17 April 2023',
      file: '',
    },
    {
      authors: 'Muhammad Fachrial Yuni Yunizar Yunus | Adnan | Christoforus Yohannes',
      year: '2019',
      tittle: 'Rancang Sistem Rumah Walet Cerdas Berbasis IOT',
      tag: 'End Devices, Node, Gateway, HTTP Request, Time on Air',
      added: '15 Mei 2023',
      file: '',
    },
    {
      authors: 'Rya Dita Purnama | Ingrid Nurtanio | Elly Warni',
      year: '2021',
      tittle: 'Implementasi Algoritma Apriori Pada Penyebab Kematian Bayi',
      tag: 'data mining, algoritma apriori, pola keterkaitan, penyebab kematian bayi',
      added: '21 Mei 2023',
      file: '',
    },
    {
      authors: 'Rizky Nadya Fatma | Ingrid Nurtanio | Andani',
      year: '2015',
      tittle: 'Sistem Prediksi Logistik Pemesanan Bahan Baku Pada Industri Makanan',
      tag: 'Prediksi, Rumah Makan, Bahan Makanan, Single Moving Average, Overstock',
      added: '21 Mei 2023',
      file: '',
    },
    // {
    //   authors: '21dwtz',
    //   year: 'Wyman',
    //   tittle: 'Jast',
    //   tag: 'Melvin.Pacocha@yahoo.com',
    //   added: 'Montana',
    //   file: 'Informatika',
    // },
    // {
    //   authors: 'o8oe4k',
    //   year: 'Janick',
    //   tittle: 'Willms',
    //   tag: 'Delfina12@gmail.com',
    //   added: 'Nebraska',
    //   file: 'Informatika',
    // },
  ];
  
  //50 us Addeds array
  export const usAddeds = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Puerto Rico',
  ];
  